In [ ]:
n = [1,2,97,3,4,98,76,4,69,96]
n = list(set(n))
for i in range (len(n)):
    for j in range(len(n)-i-1):
        if n[j] < n[j+1]:
            n[j],n[j+1] = n[j+1],n[j]
print("The second largest element is",n[1])

The second largest element is 97


In [ ]:
def freq(n):
    v = []
    for i in range(len(n)):
        if n[i] not in v:
            c = 0
            for j in range(len(n)):
                if n[i] == n[j]:
                    c+=1
            print(n[i],":",c)
        v.append(n[i])
freq([1,3,3,4,55,55,4,2,8,9])

1 : 1
3 : 2
4 : 2
55 : 2
2 : 1
8 : 1
9 : 1


In [ ]:
def remove(n):
    v = []
    for i in n:
        if i not in v:
            v.append(i)
    print(v)
remove([1,2,33,4,33,5,6,5,7,7])

[1, 2, 33, 4, 5, 6, 7]


In [ ]:
def rotate(n):
    v = [0]*len(n)
    b = 2
    k = len(n)
    for i in range(k):
        if i+2 >= k:
            v[i+2-k] = n[i]
        if i+2 < k:
            v[i+2] = n[i]
    print(v)
rotate([1,2,3,4,5,6,7])

[6, 7, 1, 2, 3, 4, 5]


In [ ]:
def pairs(n,k):
    v = []
    for i in range(len(n)):
        for j in range(i+1,len(n)):
            if n[i]+n[j] == k:
                print(n[i],n[j])
pairs([1,2,3,4,5,6,7,8,9,10,5],10)

1 9
2 8
3 7
4 6
5 5


In [ ]:
def lenof(n):
    n = sorted(n)
    c=1
    for j in range(len(n)-1):
        if n[j]+1 == n[j+1]:
            c+=1
    print(c)
lenof([100,2,4,1,6,3,20])

4


In [ ]:
def major(n):
    k=0
    v =[]
    for i in n:
        if n.count(i) > len(n)/2:
            if i not in v:
                print(i)
            v.append(i)
    if len(v) == 0:
        print("No majority element")
major([1,2,3,4,4,4,4,4])

4


In [ ]:
import numpy as np

A = np.array(eval(input("Enter Matrix A: ")))
B = np.array(eval(input("Enter Matrix B: ")))

print("Addition is:\n",A + B)
print("subtraction is:\n",A - B)
print("Multiplication is:\n",A @ B)

Enter Matrix A: [[1,2],[3,4]]
Enter Matrix B: [[5,6],[7,8]]
Addition is:
 [[ 6  8]
 [10 12]]
subtraction is:
 [[-4 -4]
 [-4 -4]]
Multiplication is:
 [[19 22]
 [43 50]]


In [2]:
def max_profit(v):
    n = []
    p = []
    for i in v:
        n.append(i)
        m = min(n)
        k = i-m
        p.append(k)
    print("The maximum profit is: ",max(p))
max_profit([7,1,5,3,6,4])

The maximum profit is:  5


In [4]:
def spiral_traversal(matrix):
    if not matrix:
        return
    top = 0
    bottom = len(matrix) - 1
    left = 0
    right = len(matrix[0]) - 1

    while top <= bottom and left <= right:

        for i in range(left, right + 1):
            print(matrix[top][i], end=" ")
        top += 1
        for i in range(top, bottom + 1):
            print(matrix[i][right], end=" ")
        right -= 1
        if top <= bottom:
            for i in range(right, left - 1, -1):
                print(matrix[bottom][i], end=" ")
            bottom -= 1
        if left <= right:
            for i in range(bottom, top - 1, -1):
                print(matrix[i][left], end=" ")
            left += 1
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))

matrix = []

print("Enter the matrix elements:")
for i in range(rows):
    row = list(map(int, input().split()))
    matrix.append(row)

print("Spiral Traversal:")
spiral_traversal(matrix)

Enter number of rows: 3
Enter number of columns: 3
Enter the matrix elements:
1 2 3
4 5 6
7 8 9
Spiral Traversal:
1 2 3 6 9 8 7 4 5 